'''
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: mouse.xml

Note: this file has been auto-generated. DO NOT EDIT
'''
from __future__ import print_function
from builtins import range
from builtins import object
import struct, array, time, json, os, sys, platform

from ...generator.mavcrc import x25crc
import hashlib

WIRE_PROTOCOL_VERSION = '2.0'
DIALECT = 'mouse'

PROTOCOL_MARKER_V1 = 0xFE
PROTOCOL_MARKER_V2 = 0xFD
HEADER_LEN_V1 = 6
HEADER_LEN_V2 = 10

MAVLINK_SIGNATURE_BLOCK_LEN = 13

MAVLINK_IFLAG_SIGNED = 0x01

native_supported = platform.system() != 'Windows' # Not yet supported on other dialects
native_force = 'MAVNATIVE_FORCE' in os.environ # Will force use of native code regardless of what client app wants
native_testing = 'MAVNATIVE_TESTING' in os.environ # Will force both native and legacy code to be used and their results compared

if native_supported and float(WIRE_PROTOCOL_VERSION) <= 1:
    try:
        import mavnative
    except ImportError:
        print('ERROR LOADING MAVNATIVE - falling back to python implementation')
        native_supported = False
else:
    # mavnative isn't supported for MAVLink2 yet
    native_supported = False

# some base types from mavlink_types.h
MAVLINK_TYPE_CHAR     = 0
MAVLINK_TYPE_UINT8_T  = 1
MAVLINK_TYPE_INT8_T   = 2
MAVLINK_TYPE_UINT16_T = 3
MAVLINK_TYPE_INT16_T  = 4
MAVLINK_TYPE_UINT32_T = 5
MAVLINK_TYPE_INT32_T  = 6
MAVLINK_TYPE_UINT64_T = 7
MAVLINK_TYPE_INT64_T  = 8
MAVLINK_TYPE_FLOAT    = 9
MAVLINK_TYPE_DOUBLE   = 10


class MAVLink_header(object):
    '''MAVLink message header'''
    def __init__(self, msgId, incompat_flags=0, compat_flags=0, mlen=0, seq=0, srcSystem=0, srcComponent=0):
        self.mlen = mlen
        self.seq = seq
        self.srcSystem = srcSystem
        self.srcComponent = srcComponent
        self.msgId = msgId
        self.incompat_flags = incompat_flags
        self.compat_flags = compat_flags

    def pack(self, force_mavlink1=False):
        if WIRE_PROTOCOL_VERSION == '2.0' and not force_mavlink1:
            return struct.pack('<BBBBBBBHB', 253, self.mlen,
                               self.incompat_flags, self.compat_flags,
                               self.seq, self.srcSystem, self.srcComponent,
                               self.msgId&0xFFFF, self.msgId>>16)
        return struct.pack('<BBBBBB', PROTOCOL_MARKER_V1, self.mlen, self.seq,
                           self.srcSystem, self.srcComponent, self.msgId)

class MAVLink_message(object):
    '''base MAVLink message class'''
    def __init__(self, msgId, name):
        self._header     = MAVLink_header(msgId)
        self._payload    = None
        self._msgbuf     = None
        self._crc        = None
        self._fieldnames = []
        self._type       = name
        self._signed     = False
        self._link_id    = None

    def format_attr(self, field):
        '''override field getter'''
        raw_attr = getattr(self,field)
        if isinstance(raw_attr, bytes):
            raw_attr = raw_attr.decode("utf-8").rstrip("\00")
        return raw_attr

    def get_msgbuf(self):
        if isinstance(self._msgbuf, bytearray):
            return self._msgbuf
        return bytearray(self._msgbuf)

    def get_header(self):
        return self._header

    def get_payload(self):
        return self._payload

    def get_crc(self):
        return self._crc

    def get_fieldnames(self):
        return self._fieldnames

    def get_type(self):
        return self._type

    def get_msgId(self):
        return self._header.msgId

    def get_srcSystem(self):
        return self._header.srcSystem

    def get_srcComponent(self):
        return self._header.srcComponent

    def get_seq(self):
        return self._header.seq

    def get_signed(self):
        return self._signed

    def get_link_id(self):
        return self._link_id

    def __str__(self):
        ret = '%s {' % self._type
        for a in self._fieldnames:
            v = self.format_attr(a)
            ret += '%s : %s, ' % (a, v)
        ret = ret[0:-2] + '}'
        return ret

    def __ne__(self, other):
        return not self.__eq__(other)

    def __eq__(self, other):
        if other is None:
            return False

        if self.get_type() != other.get_type():
            return False

        # We do not compare CRC because native code doesn't provide it
        #if self.get_crc() != other.get_crc():
        #    return False

        if self.get_seq() != other.get_seq():
            return False

        if self.get_srcSystem() != other.get_srcSystem():
            return False

        if self.get_srcComponent() != other.get_srcComponent():
            return False

        for a in self._fieldnames:
            if self.format_attr(a) != other.format_attr(a):
                return False

        return True

    def to_dict(self):
        d = dict({})
        d['mavpackettype'] = self._type
        for a in self._fieldnames:
          d[a] = self.format_attr(a)
        return d

    def to_json(self):
        return json.dumps(self.to_dict())

    def sign_packet(self, mav):
        h = hashlib.new('sha256')
        self._msgbuf += struct.pack('<BQ', mav.signing.link_id, mav.signing.timestamp)[:7]
        h.update(mav.signing.secret_key)
        h.update(self._msgbuf)
        sig = h.digest()[:6]
        self._msgbuf += sig
        mav.signing.timestamp += 1

    def pack(self, mav, crc_extra, payload, force_mavlink1=False):
        plen = len(payload)
        if WIRE_PROTOCOL_VERSION != '1.0' and not force_mavlink1:
            # in MAVLink2 we can strip trailing zeros off payloads. This allows for simple
            # variable length arrays and smaller packets
            nullbyte = chr(0)
            # in Python2, type("fred') is str but also type("fred")==bytes
            if str(type(payload)) == "<class 'bytes'>":
                nullbyte = 0
            while plen > 1 and payload[plen-1] == nullbyte:
                plen -= 1
        self._payload = payload[:plen]
        incompat_flags = 0
        if mav.signing.sign_outgoing:
            incompat_flags |= MAVLINK_IFLAG_SIGNED
        self._header  = MAVLink_header(self._header.msgId,
                                       incompat_flags=incompat_flags, compat_flags=0,
                                       mlen=len(self._payload), seq=mav.seq,
                                       srcSystem=mav.srcSystem, srcComponent=mav.srcComponent)
        self._msgbuf = self._header.pack(force_mavlink1=force_mavlink1) + self._payload
        crc = x25crc(self._msgbuf[1:])
        if True: # using CRC extra
            crc.accumulate_str(struct.pack('B', crc_extra))
        self._crc = crc.crc
        self._msgbuf += struct.pack('<H', self._crc)
        if mav.signing.sign_outgoing and not force_mavlink1:
            self.sign_packet(mav)
        return self._msgbuf


# enums

class EnumEntry(object):
    def __init__(self, name, description):
        self.name = name
        self.description = description
        self.param = {}

enums = {}

# MOUSE_MODE
enums['MOUSE_MODE'] = {}
MOUSE_MODE_STOP = 0 # All motion of mouse treadmill is stopped
enums['MOUSE_MODE'][0] = EnumEntry('MOUSE_MODE_STOP', '''All motion of mouse treadmill is stopped''')
MOUSE_MODE_SPEED = 1 # Constanst speed is applied. Speed selected by PC message
                        # SPEED_SETPOINT.
enums['MOUSE_MODE'][1] = EnumEntry('MOUSE_MODE_SPEED', '''Constanst speed is applied. Speed selected by PC message SPEED_SETPOINT.''')
MOUSE_MODE_AUTO_LOAD = 2 # Predefined speed profile is loaded
enums['MOUSE_MODE'][2] = EnumEntry('MOUSE_MODE_AUTO_LOAD', '''Predefined speed profile is loaded''')
MOUSE_MODE_AUTO_RUN = 3 # Predefined speed profile is applied
enums['MOUSE_MODE'][3] = EnumEntry('MOUSE_MODE_AUTO_RUN', '''Predefined speed profile is applied''')
MOUSE_MODE_ENUM_END = 4 # 
enums['MOUSE_MODE'][4] = EnumEntry('MOUSE_MODE_ENUM_END', '''''')

# MOUSE_ERROR
enums['MOUSE_ERROR'] = {}
MOTOR_ERROR = 0 # The motor driver flaged an error, this might be due to many sources,
                        # see datasheet of motor driver.
enums['MOUSE_ERROR'][0] = EnumEntry('MOTOR_ERROR', '''The motor driver flaged an error, this might be due to many sources, see datasheet of motor driver.''')
MOTOR_LOW_SPEED = 1 # The speed setpoint chosen is too low to be achieved.
enums['MOUSE_ERROR'][1] = EnumEntry('MOTOR_LOW_SPEED', '''The speed setpoint chosen is too low to be achieved.''')
MOTOR_HIGH_SPEED = 2 # The speed setpoint chosen is too high to be achieved.
enums['MOUSE_ERROR'][2] = EnumEntry('MOTOR_HIGH_SPEED', '''The speed setpoint chosen is too high to be achieved.''')
MOUSE_ROUTINE_TOO_LONG = 3 # More than 255 points have been defined in the mouse routine.
enums['MOUSE_ERROR'][3] = EnumEntry('MOUSE_ROUTINE_TOO_LONG', '''More than 255 points have been defined in the mouse routine.''')
SENSOR_NOT_RESPONDING = 4 # One sensor is not responding correctly.
enums['MOUSE_ERROR'][4] = EnumEntry('SENSOR_NOT_RESPONDING', '''One sensor is not responding correctly.''')
MOUSE_ERROR_ENUM_END = 5 # 
enums['MOUSE_ERROR'][5] = EnumEntry('MOUSE_ERROR_ENUM_END', '''''')

# SENSOR_ID
enums['SENSOR_ID'] = {}
SENSOR_X = 0 # Sensor ID for X direction.
enums['SENSOR_ID'][0] = EnumEntry('SENSOR_X', '''Sensor ID for X direction.''')
SENSOR_Y = 1 # Sensor ID for Y direction.
enums['SENSOR_ID'][1] = EnumEntry('SENSOR_Y', '''Sensor ID for Y direction.''')
SENSOR_ID_ENUM_END = 2 # 
enums['SENSOR_ID'][2] = EnumEntry('SENSOR_ID_ENUM_END', '''''')

# message IDs
MAVLINK_MSG_ID_BAD_DATA = -1
MAVLINK_MSG_ID_HEARTBEAT = 0
MAVLINK_MSG_ID_SPEED_INFO = 1
MAVLINK_MSG_ID_SPEED_SETPOINT = 2
MAVLINK_MSG_ID_MODE_SELECTION = 3
MAVLINK_MSG_ID_MOTOR_SETPOINT = 4
MAVLINK_MSG_ID_POINT_LOADED = 5
MAVLINK_MSG_ID_POINT = 6
MAVLINK_MSG_ID_ERROR = 7
MAVLINK_MSG_ID_RAW_SENSOR = 8

class MAVLink_heartbeat_message(MAVLink_message):
        '''
        The heartbeat message shows that a system or component is
        present and responding. Sender = STM32 Receiver = PC
        '''
        id = MAVLINK_MSG_ID_HEARTBEAT
        name = 'HEARTBEAT'
        fieldnames = ['mode', 'time']
        ordered_fieldnames = ['time', 'mode']
        fieldtypes = ['uint8_t', 'uint32_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {"mode": "MOUSE_MODE"}
        fieldunits_by_name = {}
        format = '<IB'
        native_format = bytearray('<IB', 'ascii')
        orders = [1, 0]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 137
        unpacker = struct.Struct('<IB')

        def __init__(self, mode, time):
                MAVLink_message.__init__(self, MAVLink_heartbeat_message.id, MAVLink_heartbeat_message.name)
                self._fieldnames = MAVLink_heartbeat_message.fieldnames
                self.mode = mode
                self.time = time

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 137, struct.pack('<IB', self.time, self.mode), force_mavlink1=force_mavlink1)

class MAVLink_speed_info_message(MAVLink_message):
        '''
        The message giving the actual speed of the motor. Sender =
        STM32 Receiver = PC
        '''
        id = MAVLINK_MSG_ID_SPEED_INFO
        name = 'SPEED_INFO'
        fieldnames = ['time_x', 'time_y', 'speed_x', 'speed_y', 'valid']
        ordered_fieldnames = ['time_x', 'time_y', 'speed_x', 'speed_y', 'valid']
        fieldtypes = ['uint32_t', 'uint32_t', 'float', 'float', 'uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<IIffB'
        native_format = bytearray('<IIffB', 'ascii')
        orders = [0, 1, 2, 3, 4]
        lengths = [1, 1, 1, 1, 1]
        array_lengths = [0, 0, 0, 0, 0]
        crc_extra = 243
        unpacker = struct.Struct('<IIffB')

        def __init__(self, time_x, time_y, speed_x, speed_y, valid):
                MAVLink_message.__init__(self, MAVLink_speed_info_message.id, MAVLink_speed_info_message.name)
                self._fieldnames = MAVLink_speed_info_message.fieldnames
                self.time_x = time_x
                self.time_y = time_y
                self.speed_x = speed_x
                self.speed_y = speed_y
                self.valid = valid

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 243, struct.pack('<IIffB', self.time_x, self.time_y, self.speed_x, self.speed_y, self.valid), force_mavlink1=force_mavlink1)

class MAVLink_speed_setpoint_message(MAVLink_message):
        '''
        The message is sent to send and validate the setpoint sent
        from computer. Sender = PC/STM32 Receiver = STM32/PC
        '''
        id = MAVLINK_MSG_ID_SPEED_SETPOINT
        name = 'SPEED_SETPOINT'
        fieldnames = ['setpoint_x', 'setpoint_y']
        ordered_fieldnames = ['setpoint_x', 'setpoint_y']
        fieldtypes = ['float', 'float']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<ff'
        native_format = bytearray('<ff', 'ascii')
        orders = [0, 1]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 38
        unpacker = struct.Struct('<ff')

        def __init__(self, setpoint_x, setpoint_y):
                MAVLink_message.__init__(self, MAVLink_speed_setpoint_message.id, MAVLink_speed_setpoint_message.name)
                self._fieldnames = MAVLink_speed_setpoint_message.fieldnames
                self.setpoint_x = setpoint_x
                self.setpoint_y = setpoint_y

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 38, struct.pack('<ff', self.setpoint_x, self.setpoint_y), force_mavlink1=force_mavlink1)

class MAVLink_mode_selection_message(MAVLink_message):
        '''
        This message is used to select the mode of the STM32 Sender =
        PC Receiver = STM32
        '''
        id = MAVLINK_MSG_ID_MODE_SELECTION
        name = 'MODE_SELECTION'
        fieldnames = ['mode']
        ordered_fieldnames = ['mode']
        fieldtypes = ['uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {"mode": "MOUSE_MODE"}
        fieldunits_by_name = {}
        format = '<B'
        native_format = bytearray('<B', 'ascii')
        orders = [0]
        lengths = [1]
        array_lengths = [0]
        crc_extra = 188
        unpacker = struct.Struct('<B')

        def __init__(self, mode):
                MAVLink_message.__init__(self, MAVLink_mode_selection_message.id, MAVLink_mode_selection_message.name)
                self._fieldnames = MAVLink_mode_selection_message.fieldnames
                self.mode = mode

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 188, struct.pack('<B', self.mode), force_mavlink1=force_mavlink1)

class MAVLink_motor_setpoint_message(MAVLink_message):
        '''
        This message defines the raw motor input values. This values
        defines the Duty_Cycle up time for PWM signals. Sender = STM32
        Receiver = PC
        '''
        id = MAVLINK_MSG_ID_MOTOR_SETPOINT
        name = 'MOTOR_SETPOINT'
        fieldnames = ['time', 'motor_x', 'motor_y']
        ordered_fieldnames = ['time', 'motor_x', 'motor_y']
        fieldtypes = ['uint32_t', 'float', 'float']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<Iff'
        native_format = bytearray('<Iff', 'ascii')
        orders = [0, 1, 2]
        lengths = [1, 1, 1]
        array_lengths = [0, 0, 0]
        crc_extra = 112
        unpacker = struct.Struct('<Iff')

        def __init__(self, time, motor_x, motor_y):
                MAVLink_message.__init__(self, MAVLink_motor_setpoint_message.id, MAVLink_motor_setpoint_message.name)
                self._fieldnames = MAVLink_motor_setpoint_message.fieldnames
                self.time = time
                self.motor_x = motor_x
                self.motor_y = motor_y

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 112, struct.pack('<Iff', self.time, self.motor_x, self.motor_y), force_mavlink1=force_mavlink1)

class MAVLink_point_loaded_message(MAVLink_message):
        '''
        This message is used to acknowledge the receipt of one point
        for auto mode Sender = STM32 Receiver = PC
        '''
        id = MAVLINK_MSG_ID_POINT_LOADED
        name = 'POINT_LOADED'
        fieldnames = ['point_id']
        ordered_fieldnames = ['point_id']
        fieldtypes = ['uint16_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<H'
        native_format = bytearray('<H', 'ascii')
        orders = [0]
        lengths = [1]
        array_lengths = [0]
        crc_extra = 167
        unpacker = struct.Struct('<H')

        def __init__(self, point_id):
                MAVLink_message.__init__(self, MAVLink_point_loaded_message.id, MAVLink_point_loaded_message.name)
                self._fieldnames = MAVLink_point_loaded_message.fieldnames
                self.point_id = point_id

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 167, struct.pack('<H', self.point_id), force_mavlink1=force_mavlink1)

class MAVLink_point_message(MAVLink_message):
        '''
        This message is used to send one point for auto mode. Sender =
        PC Receiver = STM32
        '''
        id = MAVLINK_MSG_ID_POINT
        name = 'POINT'
        fieldnames = ['duration', 'point_id', 'setpoint_x', 'setpoint_y']
        ordered_fieldnames = ['duration', 'setpoint_x', 'setpoint_y', 'point_id']
        fieldtypes = ['uint32_t', 'uint16_t', 'float', 'float']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<IffH'
        native_format = bytearray('<IffH', 'ascii')
        orders = [0, 3, 1, 2]
        lengths = [1, 1, 1, 1]
        array_lengths = [0, 0, 0, 0]
        crc_extra = 144
        unpacker = struct.Struct('<IffH')

        def __init__(self, duration, point_id, setpoint_x, setpoint_y):
                MAVLink_message.__init__(self, MAVLink_point_message.id, MAVLink_point_message.name)
                self._fieldnames = MAVLink_point_message.fieldnames
                self.duration = duration
                self.point_id = point_id
                self.setpoint_x = setpoint_x
                self.setpoint_y = setpoint_y

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 144, struct.pack('<IffH', self.duration, self.setpoint_x, self.setpoint_y, self.point_id), force_mavlink1=force_mavlink1)

class MAVLink_error_message(MAVLink_message):
        '''
        This message is used to send errors Sender = STM32 Receiver =
        PC
        '''
        id = MAVLINK_MSG_ID_ERROR
        name = 'ERROR'
        fieldnames = ['time', 'error']
        ordered_fieldnames = ['time', 'error']
        fieldtypes = ['uint32_t', 'uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {"error": "MOUSE_ERROR"}
        fieldunits_by_name = {}
        format = '<IB'
        native_format = bytearray('<IB', 'ascii')
        orders = [0, 1]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 22
        unpacker = struct.Struct('<IB')

        def __init__(self, time, error):
                MAVLink_message.__init__(self, MAVLink_error_message.id, MAVLink_error_message.name)
                self._fieldnames = MAVLink_error_message.fieldnames
                self.time = time
                self.error = error

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 22, struct.pack('<IB', self.time, self.error), force_mavlink1=force_mavlink1)

class MAVLink_raw_sensor_message(MAVLink_message):
        '''
        This message contains raw sensor values Sender = STM32
        Receiver = PC
        '''
        id = MAVLINK_MSG_ID_RAW_SENSOR
        name = 'RAW_SENSOR'
        fieldnames = ['time', 'sensor_id', 'delta_x', 'delta_y', 'squal', 'lift', 'product_id', 'srom_id']
        ordered_fieldnames = ['time', 'delta_x', 'delta_y', 'sensor_id', 'squal', 'lift', 'product_id', 'srom_id']
        fieldtypes = ['uint32_t', 'uint8_t', 'int16_t', 'int16_t', 'uint8_t', 'uint8_t', 'uint8_t', 'uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<IhhBBBBB'
        native_format = bytearray('<IhhBBBBB', 'ascii')
        orders = [0, 3, 1, 2, 4, 5, 6, 7]
        lengths = [1, 1, 1, 1, 1, 1, 1, 1]
        array_lengths = [0, 0, 0, 0, 0, 0, 0, 0]
        crc_extra = 75
        unpacker = struct.Struct('<IhhBBBBB')

        def __init__(self, time, sensor_id, delta_x, delta_y, squal, lift, product_id, srom_id):
                MAVLink_message.__init__(self, MAVLink_raw_sensor_message.id, MAVLink_raw_sensor_message.name)
                self._fieldnames = MAVLink_raw_sensor_message.fieldnames
                self.time = time
                self.sensor_id = sensor_id
                self.delta_x = delta_x
                self.delta_y = delta_y
                self.squal = squal
                self.lift = lift
                self.product_id = product_id
                self.srom_id = srom_id

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 75, struct.pack('<IhhBBBBB', self.time, self.delta_x, self.delta_y, self.sensor_id, self.squal, self.lift, self.product_id, self.srom_id), force_mavlink1=force_mavlink1)


mavlink_map = {
        MAVLINK_MSG_ID_HEARTBEAT : MAVLink_heartbeat_message,
        MAVLINK_MSG_ID_SPEED_INFO : MAVLink_speed_info_message,
        MAVLINK_MSG_ID_SPEED_SETPOINT : MAVLink_speed_setpoint_message,
        MAVLINK_MSG_ID_MODE_SELECTION : MAVLink_mode_selection_message,
        MAVLINK_MSG_ID_MOTOR_SETPOINT : MAVLink_motor_setpoint_message,
        MAVLINK_MSG_ID_POINT_LOADED : MAVLink_point_loaded_message,
        MAVLINK_MSG_ID_POINT : MAVLink_point_message,
        MAVLINK_MSG_ID_ERROR : MAVLink_error_message,
        MAVLINK_MSG_ID_RAW_SENSOR : MAVLink_raw_sensor_message,
}

class MAVError(Exception):
        '''MAVLink error class'''
        def __init__(self, msg):
            Exception.__init__(self, msg)
            self.message = msg

class MAVString(str):
        '''NUL terminated string'''
        def __init__(self, s):
                str.__init__(self)
        def __str__(self):
            i = self.find(chr(0))
            if i == -1:
                return self[:]
            return self[0:i]

class MAVLink_bad_data(MAVLink_message):
        '''
        a piece of bad data in a mavlink stream
        '''
        def __init__(self, data, reason):
                MAVLink_message.__init__(self, MAVLINK_MSG_ID_BAD_DATA, 'BAD_DATA')
                self._fieldnames = ['data', 'reason']
                self.data = data
                self.reason = reason
                self._msgbuf = data

        def __str__(self):
            '''Override the __str__ function from MAVLink_messages because non-printable characters are common in to be the reason for this message to exist.'''
            return '%s {%s, data:%s}' % (self._type, self.reason, [('%x' % ord(i) if isinstance(i, str) else '%x' % i) for i in self.data])

class MAVLinkSigning(object):
    '''MAVLink signing state class'''
    def __init__(self):
        self.secret_key = None
        self.timestamp = 0
        self.link_id = 0
        self.sign_outgoing = False
        self.allow_unsigned_callback = None
        self.stream_timestamps = {}
        self.sig_count = 0
        self.badsig_count = 0
        self.goodsig_count = 0
        self.unsigned_count = 0
        self.reject_count = 0

class MAVLink(object):
        '''MAVLink protocol handling class'''
        def __init__(self, file, srcSystem=0, srcComponent=0, use_native=False):
                self.seq = 0
                self.file = file
                self.srcSystem = srcSystem
                self.srcComponent = srcComponent
                self.callback = None
                self.callback_args = None
                self.callback_kwargs = None
                self.send_callback = None
                self.send_callback_args = None
                self.send_callback_kwargs = None
                self.buf = bytearray()
                self.buf_index = 0
                self.expected_length = HEADER_LEN_V1+2
                self.have_prefix_error = False
                self.robust_parsing = False
                self.protocol_marker = 253
                self.little_endian = True
                self.crc_extra = True
                self.sort_fields = True
                self.total_packets_sent = 0
                self.total_bytes_sent = 0
                self.total_packets_received = 0
                self.total_bytes_received = 0
                self.total_receive_errors = 0
                self.startup_time = time.time()
                self.signing = MAVLinkSigning()
                if native_supported and (use_native or native_testing or native_force):
                    print("NOTE: mavnative is currently beta-test code")
                    self.native = mavnative.NativeConnection(MAVLink_message, mavlink_map)
                else:
                    self.native = None
                if native_testing:
                    self.test_buf = bytearray()
                self.mav20_unpacker = struct.Struct('<cBBBBBBHB')
                self.mav10_unpacker = struct.Struct('<cBBBBB')
                self.mav20_h3_unpacker = struct.Struct('BBB')
                self.mav_csum_unpacker = struct.Struct('<H')
                self.mav_sign_unpacker = struct.Struct('<IH')

        def set_callback(self, callback, *args, **kwargs):
            self.callback = callback
            self.callback_args = args
            self.callback_kwargs = kwargs

        def set_send_callback(self, callback, *args, **kwargs):
            self.send_callback = callback
            self.send_callback_args = args
            self.send_callback_kwargs = kwargs

        def send(self, mavmsg, force_mavlink1=False):
                '''send a MAVLink message'''
                buf = mavmsg.pack(self, force_mavlink1=force_mavlink1)
                self.file.write(buf)
                self.seq = (self.seq + 1) % 256
                self.total_packets_sent += 1
                self.total_bytes_sent += len(buf)
                if self.send_callback:
                    self.send_callback(mavmsg, *self.send_callback_args, **self.send_callback_kwargs)

        def buf_len(self):
            return len(self.buf) - self.buf_index

        def bytes_needed(self):
            '''return number of bytes needed for next parsing stage'''
            if self.native:
                ret = self.native.expected_length - self.buf_len()
            else:
                ret = self.expected_length - self.buf_len()

            if ret <= 0:
                return 1
            return ret

        def __parse_char_native(self, c):
            '''this method exists only to see in profiling results'''
            m = self.native.parse_chars(c)
            return m

        def __callbacks(self, msg):
            '''this method exists only to make profiling results easier to read'''
            if self.callback:
                self.callback(msg, *self.callback_args, **self.callback_kwargs)

        def parse_char(self, c):
            '''input some data bytes, possibly returning a new message'''
            self.buf.extend(c)

            self.total_bytes_received += len(c)

            if self.native:
                if native_testing:
                    self.test_buf.extend(c)
                    m = self.__parse_char_native(self.test_buf)
                    m2 = self.__parse_char_legacy()
                    if m2 != m:
                        print("Native: %s\nLegacy: %s\n" % (m, m2))
                        raise Exception('Native vs. Legacy mismatch')
                else:
                    m = self.__parse_char_native(self.buf)
            else:
                m = self.__parse_char_legacy()

            if m is not None:
                self.total_packets_received += 1
                self.__callbacks(m)
            else:
                # XXX The idea here is if we've read something and there's nothing left in
                # the buffer, reset it to 0 which frees the memory
                if self.buf_len() == 0 and self.buf_index != 0:
                    self.buf = bytearray()
                    self.buf_index = 0

            return m

        def __parse_char_legacy(self):
            '''input some data bytes, possibly returning a new message (uses no native code)'''
            header_len = HEADER_LEN_V1
            if self.buf_len() >= 1 and self.buf[self.buf_index] == PROTOCOL_MARKER_V2:
                header_len = HEADER_LEN_V2

            if self.buf_len() >= 1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V2:
                magic = self.buf[self.buf_index]
                self.buf_index += 1
                if self.robust_parsing:
                    m = MAVLink_bad_data(bytearray([magic]), 'Bad prefix')
                    self.expected_length = header_len+2
                    self.total_receive_errors += 1
                    return m
                if self.have_prefix_error:
                    return None
                self.have_prefix_error = True
                self.total_receive_errors += 1
                raise MAVError("invalid MAVLink prefix '%s'" % magic)
            self.have_prefix_error = False
            if self.buf_len() >= 3:
                sbuf = self.buf[self.buf_index:3+self.buf_index]
                if sys.version_info.major < 3:
                    sbuf = str(sbuf)
                (magic, self.expected_length, incompat_flags) = self.mav20_h3_unpacker.unpack(sbuf)
                if magic == PROTOCOL_MARKER_V2 and (incompat_flags & MAVLINK_IFLAG_SIGNED):
                        self.expected_length += MAVLINK_SIGNATURE_BLOCK_LEN
                self.expected_length += header_len + 2
            if self.expected_length >= (header_len+2) and self.buf_len() >= self.expected_length:
                mbuf = array.array('B', self.buf[self.buf_index:self.buf_index+self.expected_length])
                self.buf_index += self.expected_length
                self.expected_length = header_len+2
                if self.robust_parsing:
                    try:
                        if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                            raise MAVError('invalid incompat_flags 0x%x 0x%x %u' % (incompat_flags, magic, self.expected_length))
                        m = self.decode(mbuf)
                    except MAVError as reason:
                        m = MAVLink_bad_data(mbuf, reason.message)
                        self.total_receive_errors += 1
                else:
                    if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                        raise MAVError('invalid incompat_flags 0x%x 0x%x %u' % (incompat_flags, magic, self.expected_length))
                    m = self.decode(mbuf)
                return m
            return None

        def parse_buffer(self, s):
            '''input some data bytes, possibly returning a list of new messages'''
            m = self.parse_char(s)
            if m is None:
                return None
            ret = [m]
            while True:
                m = self.parse_char("")
                if m is None:
                    return ret
                ret.append(m)
            return ret

        def check_signature(self, msgbuf, srcSystem, srcComponent):
            '''check signature on incoming message'''
            if isinstance(msgbuf, array.array):
                msgbuf = msgbuf.tostring()
            timestamp_buf = msgbuf[-12:-6]
            link_id = msgbuf[-13]
            (tlow, thigh) = self.mav_sign_unpacker.unpack(timestamp_buf)
            timestamp = tlow + (thigh<<32)

            # see if the timestamp is acceptable
            stream_key = (link_id,srcSystem,srcComponent)
            if stream_key in self.signing.stream_timestamps:
                if timestamp <= self.signing.stream_timestamps[stream_key]:
                    # reject old timestamp
                    # print('old timestamp')
                    return False
            else:
                # a new stream has appeared. Accept the timestamp if it is at most
                # one minute behind our current timestamp
                if timestamp + 6000*1000 < self.signing.timestamp:
                    # print('bad new stream ', timestamp/(100.0*1000*60*60*24*365), self.signing.timestamp/(100.0*1000*60*60*24*365))
                    return False
                self.signing.stream_timestamps[stream_key] = timestamp
                # print('new stream')

            h = hashlib.new('sha256')
            h.update(self.signing.secret_key)
            h.update(msgbuf[:-6])
            if str(type(msgbuf)) == "<class 'bytes'>":
                # Python 3
                sig1 = h.digest()[:6]
                sig2 = msgbuf[-6:]
            else:
                sig1 = str(h.digest())[:6]
                sig2 = str(msgbuf)[-6:]
            if sig1 != sig2:
                # print('sig mismatch')
                return False

            # the timestamp we next send with is the max of the received timestamp and
            # our current timestamp
            self.signing.timestamp = max(self.signing.timestamp, timestamp)
            return True

        def decode(self, msgbuf):
                '''decode a buffer as a MAVLink message'''
                # decode the header
                if msgbuf[0] != PROTOCOL_MARKER_V1:
                    headerlen = 10
                    try:
                        magic, mlen, incompat_flags, compat_flags, seq, srcSystem, srcComponent, msgIdlow, msgIdhigh = self.mav20_unpacker.unpack(msgbuf[:headerlen])
                    except struct.error as emsg:
                        raise MAVError('Unable to unpack MAVLink header: %s' % emsg)
                    msgId = msgIdlow | (msgIdhigh<<16)
                    mapkey = msgId
                else:
                    headerlen = 6
                    try:
                        magic, mlen, seq, srcSystem, srcComponent, msgId = self.mav10_unpacker.unpack(msgbuf[:headerlen])
                        incompat_flags = 0
                        compat_flags = 0
                    except struct.error as emsg:
                        raise MAVError('Unable to unpack MAVLink header: %s' % emsg)
                    mapkey = msgId
                if (incompat_flags & MAVLINK_IFLAG_SIGNED) != 0:
                    signature_len = MAVLINK_SIGNATURE_BLOCK_LEN
                else:
                    signature_len = 0

                if ord(magic) != PROTOCOL_MARKER_V1 and ord(magic) != PROTOCOL_MARKER_V2:
                    raise MAVError("invalid MAVLink prefix '%s'" % magic)
                if mlen != len(msgbuf)-(headerlen+2+signature_len):
                    raise MAVError('invalid MAVLink message length. Got %u expected %u, msgId=%u headerlen=%u' % (len(msgbuf)-(headerlen+2+signature_len), mlen, msgId, headerlen))

                if not mapkey in mavlink_map:
                    raise MAVError('unknown MAVLink message ID %s' % str(mapkey))

                # decode the payload
                type = mavlink_map[mapkey]
                fmt = type.format
                order_map = type.orders
                len_map = type.lengths
                crc_extra = type.crc_extra

                # decode the checksum
                try:
                    crc, = self.mav_csum_unpacker.unpack(msgbuf[-(2+signature_len):][:2])
                except struct.error as emsg:
                    raise MAVError('Unable to unpack MAVLink CRC: %s' % emsg)
                crcbuf = msgbuf[1:-(2+signature_len)]
                if True: # using CRC extra
                    crcbuf.append(crc_extra)
                crc2 = x25crc(crcbuf)
                if crc != crc2.crc:
                    raise MAVError('invalid MAVLink CRC in msgID %u 0x%04x should be 0x%04x' % (msgId, crc, crc2.crc))

                sig_ok = False
                if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
                    self.signing.sig_count += 1
                if self.signing.secret_key is not None:
                    accept_signature = False
                    if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
                        sig_ok = self.check_signature(msgbuf, srcSystem, srcComponent)
                        accept_signature = sig_ok
                        if sig_ok:
                            self.signing.goodsig_count += 1
                        else:
                            self.signing.badsig_count += 1
                        if not accept_signature and self.signing.allow_unsigned_callback is not None:
                            accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                            if accept_signature:
                                self.signing.unsigned_count += 1
                            else:
                                self.signing.reject_count += 1
                    elif self.signing.allow_unsigned_callback is not None:
                        accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                        if accept_signature:
                            self.signing.unsigned_count += 1
                        else:
                            self.signing.reject_count += 1
                    if not accept_signature:
                        raise MAVError('Invalid signature')

                csize = type.unpacker.size
                mbuf = msgbuf[headerlen:-(2+signature_len)]
                if len(mbuf) < csize:
                    # zero pad to give right size
                    mbuf.extend([0]*(csize - len(mbuf)))
                if len(mbuf) < csize:
                    raise MAVError('Bad message of type %s length %u needs %s' % (
                        type, len(mbuf), csize))
                mbuf = mbuf[:csize]
                try:
                    t = type.unpacker.unpack(mbuf)
                except struct.error as emsg:
                    raise MAVError('Unable to unpack MAVLink payload type=%s fmt=%s payloadLength=%u: %s' % (
                        type, fmt, len(mbuf), emsg))

                tlist = list(t)
                # handle sorted fields
                if True:
                    t = tlist[:]
                    if sum(len_map) == len(len_map):
                        # message has no arrays in it
                        for i in range(0, len(tlist)):
                            tlist[i] = t[order_map[i]]
                    else:
                        # message has some arrays
                        tlist = []
                        for i in range(0, len(order_map)):
                            order = order_map[i]
                            L = len_map[order]
                            tip = sum(len_map[:order])
                            field = t[tip]
                            if L == 1 or isinstance(field, str):
                                tlist.append(field)
                            else:
                                tlist.append(t[tip:(tip + L)])

                # terminate any strings
                for i in range(0, len(tlist)):
                    if type.fieldtypes[i] == 'char':
                        if sys.version_info.major >= 3:
                            tlist[i] = tlist[i].decode('utf-8')
                        tlist[i] = str(MAVString(tlist[i]))
                t = tuple(tlist)
                # construct the message object
                try:
                    m = type(*t)
                except Exception as emsg:
                    raise MAVError('Unable to instantiate MAVLink message of type %s : %s' % (type, emsg))
                m._signed = sig_ok
                if m._signed:
                    m._link_id = msgbuf[-13]
                m._msgbuf = msgbuf
                m._payload = msgbuf[6:-(2+signature_len)]
                m._crc = crc
                m._header = MAVLink_header(msgId, incompat_flags, compat_flags, mlen, seq, srcSystem, srcComponent)
                return m
        def heartbeat_encode(self, mode, time):
                '''
                The heartbeat message shows that a system or component is present and
                responding. Sender = STM32 Receiver = PC

                mode                      : Actual operating mode (type:uint8_t, values:MOUSE_MODE)
                time                      : Time from boot of system (type:uint32_t)

                '''
                return MAVLink_heartbeat_message(mode, time)

        def heartbeat_send(self, mode, time, force_mavlink1=False):
                '''
                The heartbeat message shows that a system or component is present and
                responding. Sender = STM32 Receiver = PC

                mode                      : Actual operating mode (type:uint8_t, values:MOUSE_MODE)
                time                      : Time from boot of system (type:uint32_t)

                '''
                return self.send(self.heartbeat_encode(mode, time), force_mavlink1=force_mavlink1)

        def speed_info_encode(self, time_x, time_y, speed_x, speed_y, valid):
                '''
                The message giving the actual speed of the motor. Sender = STM32
                Receiver = PC

                time_x                    : Time from boot of system for speed_x measure (type:uint32_t)
                time_y                    : Time from boot of system for speed_y measure (type:uint32_t)
                speed_x                   : Speed in x direction (type:float)
                speed_y                   : Speed in y direction (type:float)
                valid                     : 0 if data are not valid, 1 if data are valid (type:uint8_t)

                '''
                return MAVLink_speed_info_message(time_x, time_y, speed_x, speed_y, valid)

        def speed_info_send(self, time_x, time_y, speed_x, speed_y, valid, force_mavlink1=False):
                '''
                The message giving the actual speed of the motor. Sender = STM32
                Receiver = PC

                time_x                    : Time from boot of system for speed_x measure (type:uint32_t)
                time_y                    : Time from boot of system for speed_y measure (type:uint32_t)
                speed_x                   : Speed in x direction (type:float)
                speed_y                   : Speed in y direction (type:float)
                valid                     : 0 if data are not valid, 1 if data are valid (type:uint8_t)

                '''
                return self.send(self.speed_info_encode(time_x, time_y, speed_x, speed_y, valid), force_mavlink1=force_mavlink1)

        def speed_setpoint_encode(self, setpoint_x, setpoint_y):
                '''
                The message is sent to send and validate the setpoint sent from
                computer. Sender = PC/STM32 Receiver = STM32/PC

                setpoint_x                : Speed setpoint in x direction (type:float)
                setpoint_y                : Speed setpoint in y direction (type:float)

                '''
                return MAVLink_speed_setpoint_message(setpoint_x, setpoint_y)

        def speed_setpoint_send(self, setpoint_x, setpoint_y, force_mavlink1=False):
                '''
                The message is sent to send and validate the setpoint sent from
                computer. Sender = PC/STM32 Receiver = STM32/PC

                setpoint_x                : Speed setpoint in x direction (type:float)
                setpoint_y                : Speed setpoint in y direction (type:float)

                '''
                return self.send(self.speed_setpoint_encode(setpoint_x, setpoint_y), force_mavlink1=force_mavlink1)

        def mode_selection_encode(self, mode):
                '''
                This message is used to select the mode of the STM32 Sender = PC
                Receiver = STM32

                mode                      : Actual operating mode (type:uint8_t, values:MOUSE_MODE)

                '''
                return MAVLink_mode_selection_message(mode)

        def mode_selection_send(self, mode, force_mavlink1=False):
                '''
                This message is used to select the mode of the STM32 Sender = PC
                Receiver = STM32

                mode                      : Actual operating mode (type:uint8_t, values:MOUSE_MODE)

                '''
                return self.send(self.mode_selection_encode(mode), force_mavlink1=force_mavlink1)

        def motor_setpoint_encode(self, time, motor_x, motor_y):
                '''
                This message defines the raw motor input values. This values defines
                the Duty_Cycle up time for PWM signals. Sender = STM32
                Receiver = PC

                time                      : Time from boot of system (type:uint32_t)
                motor_x                   : Speed setpoint in x direction (type:float)
                motor_y                   : Speed setpoint in y direction (type:float)

                '''
                return MAVLink_motor_setpoint_message(time, motor_x, motor_y)

        def motor_setpoint_send(self, time, motor_x, motor_y, force_mavlink1=False):
                '''
                This message defines the raw motor input values. This values defines
                the Duty_Cycle up time for PWM signals. Sender = STM32
                Receiver = PC

                time                      : Time from boot of system (type:uint32_t)
                motor_x                   : Speed setpoint in x direction (type:float)
                motor_y                   : Speed setpoint in y direction (type:float)

                '''
                return self.send(self.motor_setpoint_encode(time, motor_x, motor_y), force_mavlink1=force_mavlink1)

        def point_loaded_encode(self, point_id):
                '''
                This message is used to acknowledge the receipt of one point for auto
                mode Sender = STM32 Receiver = PC

                point_id                  : Last ID of point loaded (type:uint16_t)

                '''
                return MAVLink_point_loaded_message(point_id)

        def point_loaded_send(self, point_id, force_mavlink1=False):
                '''
                This message is used to acknowledge the receipt of one point for auto
                mode Sender = STM32 Receiver = PC

                point_id                  : Last ID of point loaded (type:uint16_t)

                '''
                return self.send(self.point_loaded_encode(point_id), force_mavlink1=force_mavlink1)

        def point_encode(self, duration, point_id, setpoint_x, setpoint_y):
                '''
                This message is used to send one point for auto mode. Sender = PC
                Receiver = STM32

                duration                  : Time during which the setpoint need to be kept (type:uint32_t)
                point_id                  : point ID (type:uint16_t)
                setpoint_x                : Speed setpoint in x direction (type:float)
                setpoint_y                : Speed setpoint in y direction (type:float)

                '''
                return MAVLink_point_message(duration, point_id, setpoint_x, setpoint_y)

        def point_send(self, duration, point_id, setpoint_x, setpoint_y, force_mavlink1=False):
                '''
                This message is used to send one point for auto mode. Sender = PC
                Receiver = STM32

                duration                  : Time during which the setpoint need to be kept (type:uint32_t)
                point_id                  : point ID (type:uint16_t)
                setpoint_x                : Speed setpoint in x direction (type:float)
                setpoint_y                : Speed setpoint in y direction (type:float)

                '''
                return self.send(self.point_encode(duration, point_id, setpoint_x, setpoint_y), force_mavlink1=force_mavlink1)

        def error_encode(self, time, error):
                '''
                This message is used to send errors Sender = STM32 Receiver = PC

                time                      : Time from boot of system (type:uint32_t)
                error                     : error ID (type:uint8_t, values:MOUSE_ERROR)

                '''
                return MAVLink_error_message(time, error)

        def error_send(self, time, error, force_mavlink1=False):
                '''
                This message is used to send errors Sender = STM32 Receiver = PC

                time                      : Time from boot of system (type:uint32_t)
                error                     : error ID (type:uint8_t, values:MOUSE_ERROR)

                '''
                return self.send(self.error_encode(time, error), force_mavlink1=force_mavlink1)

        def raw_sensor_encode(self, time, sensor_id, delta_x, delta_y, squal, lift, product_id, srom_id):
                '''
                This message contains raw sensor values Sender = STM32 Receiver = PC

                time                      : Time from boot of system (type:uint32_t)
                sensor_id                 : 0 for X, 1 for Y. (type:uint8_t)
                delta_x                   : Displacement along sensor's x in counts per inch. (type:int16_t)
                delta_y                   : Displacement along sensor's y in counts per inch. (type:int16_t)
                squal                     : Quality of the surface. For white paper is around 30. (type:uint8_t)
                lift                      : 1 if the sensor is lifted (not measuring). 0 otherwise (type:uint8_t)
                product_id                : 0x42 if the serial communication with the sensor works correctly. (type:uint8_t)
                srom_id                   : 0x00 if initialisation is not done. Other value if done correctly. (type:uint8_t)

                '''
                return MAVLink_raw_sensor_message(time, sensor_id, delta_x, delta_y, squal, lift, product_id, srom_id)

        def raw_sensor_send(self, time, sensor_id, delta_x, delta_y, squal, lift, product_id, srom_id, force_mavlink1=False):
                '''
                This message contains raw sensor values Sender = STM32 Receiver = PC

                time                      : Time from boot of system (type:uint32_t)
                sensor_id                 : 0 for X, 1 for Y. (type:uint8_t)
                delta_x                   : Displacement along sensor's x in counts per inch. (type:int16_t)
                delta_y                   : Displacement along sensor's y in counts per inch. (type:int16_t)
                squal                     : Quality of the surface. For white paper is around 30. (type:uint8_t)
                lift                      : 1 if the sensor is lifted (not measuring). 0 otherwise (type:uint8_t)
                product_id                : 0x42 if the serial communication with the sensor works correctly. (type:uint8_t)
                srom_id                   : 0x00 if initialisation is not done. Other value if done correctly. (type:uint8_t)

                '''
                return self.send(self.raw_sensor_encode(time, sensor_id, delta_x, delta_y, squal, lift, product_id, srom_id), force_mavlink1=force_mavlink1)

